PRAGMA foreign_keys = ON;
CREATE TABLE Department (
 Dno TEXT PRIMARY KEY NOT NULL,
 Dname TEXT NOT NULL UNIQUE,
 Dean TEXT NOT NULL
);
CREATE TABLE Student (
 Sno TEXT PRIMARY KEY NOT NULL,
 Sname TEXT NOT NULL,
 Ssex TEXT NOT NULL,
 Sage INTEGER NOT NULL CHECK(Sage > 0),
 Dno TEXT NOT NULL REFERENCES Department(Dno)
);
CREATE TABLE Teacher (
 Tno TEXT PRIMARY KEY NOT NULL,
 Tname TEXT NOT NULL UNIQUE,
 Ttitle TEXT NOT NULL,
 Dno TEXT NOT NULL REFERENCES Department(Dno)
);
CREATE TABLE Course (
 Cno TEXT PRIMARY KEY NOT NULL,
 Cname TEXT NOT NULL UNIQUE,
 Credit REAL NOT NULL CHECK(Credit > 0),
 Cdept TEXT NOT NULL REFERENCES Department(Dno),
 Tno TEXT NOT NULL REFERENCES Teacher(Tno)
);
CREATE TABLE SC (
 Sno TEXT NOT NULL REFERENCES Student(Sno),
 Cno TEXT NOT NULL REFERENCES Course(Cno),
 Grade REAL CHECK(Grade IS NULL OR Grade BETWEEN 0 AND 100),
 PRIMARY KEY(Sno, Cno)
);
CREATE TABLE Prerequisite (
 Cno TEXT NOT NULL REFERENCES Course(Cno),
 Pno TEXT NOT NULL REFERENCES Course(Cno),
 PRIMARY KEY(Cno, Pno),
 CHECK(Cno <> Pno)
);
CREATE INDEX idx_student_department ON Student(Dno);
CREATE INDEX idx_sc_course ON SC(Cno);
